# Setup
title:        Rika Tanudjaja
tagline:      Sometimes all it takes is one step forward
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Rika Tanudjaja
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
