# Setup
title:        Rika Tanudjaja
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Rika Tanudjaja
  url:        http://rikatanudjaja.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
